config/routes.rb
Rails.application.routes.draw do
  post 'alexa', to: 'alexa#index'
  resources :talks
  root to: 'visitors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/talk.rb
require "#{Rails.root}/lib/travis_api"
require "#{Rails.root}/lib/post_to_chat"

# It's all about the talks
class Talk < ApplicationRecord
  def self.find_talk(foo) # rubocop:disable Metrics/MethodLength
    @chat = PostToChat.new('https://friendsterbookspace.herokuapp.com/')
    days_of_conf = {'2017-04-25' => '1', '2017-04-26' => '2', '2017-04-27' => '3',
                    'today' => '1', 'tomorrow' => '2', 'thursday' => '3'}
    puts "FOO: #{foo.inspect}"
    date     = nil
    location = nil
    person   = nil
    talk     = nil
    time     = nil
    repo     = nil

    if foo['Date']
      date = days_of_conf[foo['Date']['value']]
    end
    if foo['SpokenDate']
      date = days_of_conf[foo['SpokenDate']['value']]
    end
    if foo['Talk']
      talk = foo['Talk']['value'].titlecase unless foo['Talk']['value'].blank?
    end
    if foo['Speaker']
      person = foo['Speaker']['value']
      if person == 'iron' # Gah Alexa keeps thinking I'm saying iron
        person = 'Aaron'
      end
    end
    if foo['Time']
      time = foo['Time']['value']
    end
    if foo['Location']
      location = foo['Location']['value'].titlecase unless foo['Location']['value'].blank?
    end
    if foo['Repo']
      repo = foo['Repo']['value'].titlecase unless foo['Repo']['value'].blank?
    end

    results = finder(date, location, person, repo, talk, time)
    puts "Results: #{results.inspect}"
    generate_response(results, location, person, repo, talk, time)
  end

  def self.finder(date, location, person, repo, talk, time)
    puts "DATE: #{date}"
    puts "Time: #{time}"
    puts "TALK: #{talk}"
    puts "LOCATION: #{location}"
    puts "PERSON: #{person}"
    puts "REPO: #{repo}"
    results = ""
    if talk
      results = where(conference_day: date).where('title like ?', "%#{talk}%")
      if talk == 'Talk Introduction'
        results = ['foo','bar']
      end
    end
    if person
      results = where('presenter like ?', "%#{person}%")
    end
    if time
      results = where(conference_day: date, start_time: time).where('room like ?', "%#{location}%")
    end
    if repo
      results = ['foo', 'bar']
    end
    results
  end

  def self.generate_response(results, location=nil, person=nil, repo=nil, talk=nil, time=nil)
    if results.nil?
      response_string = "Sorry, couldn't understand the question. Please ask again"
      @chat.post_message(response_string)
      return response_string
    end
    if results.empty?
      response_string = "Sorry, couldn't find a thing. Let's try that again"
      @chat.post_message(response_string)
      return response_string
    end
    response_string = ''
    if talk == 'Keynote'
      if results.size > 1
        response_string =
          "There are #{results.size} #{talk}s, both are in the #{results.first.room}"
      end
    end
    if talk == 'Talk Introduction'
      response_string =
        "Sup! I'm Alexa, This is my first Rails conference. How you enjoying it? It's so hot here in Phoenix, you'd think I'd be used to that being from the Amazon. I love DHH, he writes the best codes and rants so well about shitty startups. I also really like Tender love, but I can beat his puns any day. Come at me bro! Just joking Tender love. Here is some advice. Don't give up on your dreams. Keep sleeping."
    end
    if person
      if results.size < 2
      response_string =
        "What an exciting talk that #{results.first.presenter} is giving. It's about #{results.first.title}, in room #{results.first.room} at #{results.first.start_time.strftime("%H:%M:%S")}."
        if results.first.presenter == "Aaron Patterson"
          response_string << " Let's hope he has some good puns, for once!"
        end
      end
    end
    if time
      if results.first.title == 'LUNCH' || results.first.title == 'AM BREAK' || results.first.title == 'PM BREAK'
        response_string = "Ooh such excite, looks like it's time for #{results.first.title}"
      else
        string_builder = ""
        results.each do |result|
          string_builder << "#{result.presenter}, #{result.title},"
        end
        response_string = "Well we have; #{string_builder}. Overall a pretty decent lineup. I think you should see #{results.sample.presenter}'s talk'"
      end
    end
    if repo == 'Rails'
      travis = TravisAPI.new
      response_string =
        travis.build_status('rails/rails')
    end
    @chat.post_message(response_string)
    response_string
  end
end

# where(conference_day: date, room: location, presenter: person, start_time: time)

app/controllers/alexa_controller.rb
require 'alexa_rubykit'
# Uber Alexa Controller. Can you even control Alexa?
class AlexaController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    alexa = AlexaRubykit.build_request(JSON.parse(request.body.read.to_s))

    # @intent={"name"=>"RailsConfTalks", "slots"=>{"Date"=>{"name"=>"Date"}}},
    # @type="INTENT_REQUEST", @name="RailsConfTalks",
    # @slots={"Date"=>{"name"=>"Date"}}>

    response = generate_response(alexa)

    render json: response
  end

  private

  def generate_response(alexa) # rubocop:disable Metrics/MethodLength
    alexa_response = AlexaRubykit::Response.new

    speach_string = which_demo_am_i_calling(alexa)
    puts speach_string

    case alexa.type
    when 'INTENT_REQUEST'
      alexa_response.add_speech(speach_string)
      alexa_response.add_hash_card(title: 'AlexaOnRails',
                                   subtitle: "Intent #{alexa.name}")
    when 'SESSION_ENDED_REQUEST'
      halt 200
    end
    alexa_response.build_response
  end

  def which_demo_am_i_calling(which_one)
    response_string = ''
    case which_one.name
    when 'RailsConfTalks'
      response_string = Talk.find_talk(which_one.slots)
    end
    response_string
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/talks_controller.rb
# Talks Controller, does what it says on the tin
class TalksController < ApplicationController
  before_action :set_talk, only: [:show]

  # GET /talks
  # GET /talks.json
  def index
    respond_to do |format|
      format.html { @talks = Talk.all }
      format.json { render json: Talk.all }
    end
  end

  # GET /talks/1
  # GET /talks/1.json
  def show
    respond_to do |format|
      format.html { @talk }
      format.json { render json: @talk }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_talk
    @talk = Talk.find(params[:id])
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/alexa_helper.rb
module AlexaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Rails bootstrap", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Bootstrap" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <% render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/talks/_form.html.erb
<%= form_for(talk) do |f| %>
  <% if talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(talk.errors.count, "error") %> prohibited this talk from being saved:</h2>

      <ul>
      <% talk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/talks/edit.html.erb
<h1>Editing Talk</h1>

<%= render 'form', talk: @talk %>

<%= link_to 'Show', @talk %> |
<%= link_to 'Back', talks_path %>

app/views/talks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Talks</h1>

<table>
  <thead>
    <tr>
      <th>Conference Day</th>
      <th>Title</th>
      <th>Presenter</th>
    </tr>
  </thead>

  <tbody>
    <% @talks.each do |talk| %>
      <tr>
        <td><%= talk.conference_day %></td>
        <td><%= link_to talk.title, talk %></td>
        <td><%= talk.presenter %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/talks/new.html.erb
<h1>New Talk</h1>

<%= render 'form', talk: @talk %>

<%= link_to 'Back', talks_path %>

app/views/talks/show.html.erb
<b>Conferance Day</b> <%= @talk.conference_day %></br>
<b>Start Time</b> <%= @talk.start_time.strftime("%H:%M:%S") %></br>
<b>End Time</b> <%= @talk.end_time.strftime("%H:%M:%S") %></br>
<b>Session ID</b> <%= @talk.program_session_id %></br>
<b>Title</b> <%= @talk.title %></br>
<b>Presenter</b> <%= @talk.presenter %></br>
<b>Room</b> <%= @talk.room %></br>
<b>Track</b> <%= @talk.track %></br>
<b>Description</b> <%= @talk.description %></br>

<%= link_to 'Back', talks_path %>

app/views/visitors/index.html.erb
<h3>Welcome</h3>

<h4><%= link_to('Talks', talks_path) %><h4>